# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f31d6b72c73b486069dfb9f6eeaa26a003ac9cddd9334cd7a771edd537b59aa93fc78291c2c57a23ead3b3fb6ddcb3b73a3a660a7550ca01af20bcb058f333d0

test:
  secret_key_base: 997503c2aadfa472021bd4be68ed4313c28e2692a7c6a21b6e56455a3a4ae24216d705bf7d3a17f958cec299488b45772397702bd993f7f69aae8990f726199e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
